package oris.view;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import oris.view.models.TableModelSegmentos;
import oris.view.models.ComboModelPosicion;
import oris.view.models.ComboModelMoneda;
import oris.view.models.ComboModelEstado;
import oris.view.models.ComboModelTipo;
import oris.view.models.ComboModelTipoPax;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import oris.model.dao.TicketDAO;
import oris.model.dto.Ticket;


/**
 *
 * @author Felipe
 */
public class DetalleRegistro extends javax.swing.JDialog {

    /**
     * Creates new form DetalleRegistro
     */
    private ComboModelTipo tipos;
    private ComboModelMoneda monedas;
    private ComboModelEstado estados;
    private ComboModelTipoPax tipo_paxs;
    private ComboModelPosicion posiciones;
    private boolean isNuevo;
    private boolean isModificado = false;

    public DetalleRegistro(Ticket ticket, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tipos = new ComboModelTipo();
        monedas = new ComboModelMoneda();
        estados = new ComboModelEstado();
        tipo_paxs = new ComboModelTipoPax();
        posiciones = new ComboModelPosicion();
        if (ticket != null) {//el ticket no es nuevo
            isNuevo = false;

            ticket.setGds("A");
            tipos.setSelectedItem(ticket.getTipo());
            estados.setSelectedItem(ticket.getEstado());
            monedas.setSelectedItem(ticket.getMoneda());
            tipo_paxs.setSelectedItem(ticket.getTipoPasajero());
            posiciones.setSelectedItem(ticket.getPosicion());

            this.txt_ticket.setText(ticket.getTicket());
            this.txt_num_file.setText(ticket.getNumFile());
            this.txt_reemitido.setText(ticket.getOldTicket());
            this.txt_pnr.setText(ticket.getPnr());
            this.txt_emd.setText(ticket.getCodEmd());
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
            try {
                this.date_fecha_emi.setDate(sdf.parse(ticket.getFechaEmision()));
                this.date_fecha_anu.setDate(sdf.parse(ticket.getFechaAnulacion()));
                this.date_fecha_ree.setDate(sdf.parse(ticket.getFechaRemision()));
            } catch (ParseException ex) {
                ex.printStackTrace();
            }

            this.txt_nombre_pax.setText(ticket.getNombrePasajero());
            this.txt_fpago.setText(ticket.getfPago());

            //DecimalFormat df = new DecimalFormat("#,##");
            this.txt_comision.setValue(ticket.getComision());
            this.txt_valor_neto.setValue(ticket.getValorNeto());
            this.txt_valor_tax.setValue(ticket.getValorTasas());
            this.txt_valor_final.setValue(ticket.getValorFinal());

            this.txt_codigo_la.setText(ticket.getcLineaAerea());
            this.txt_ruta.setText(ticket.getRuta());
            TableModelSegmentos segmentos_model = new TableModelSegmentos(ticket);
            this.table_segmentos.setModel(segmentos_model);
            this.txt_ticket.setEditable(false);
        } else {//elt ticket es nuevo
            isNuevo = true;
            tipos = new ComboModelTipo();
            this.cmb_tipo.setModel(tipos);

            java.util.Date fecha = new Date();
            this.date_fecha_emi.setDate(fecha);
            this.txt_comision.setValue(new Double("0.00"));
            this.txt_valor_final.setValue(new Double("0.00"));
            this.txt_valor_neto.setValue(new Double("0.00"));
            this.txt_valor_tax.setValue(new Double("0.00"));
        }

        this.table_segmentos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        this.cmb_estado.setModel(estados);
        this.cmb_moneda.setModel(monedas);
        this.cmb_tipo.setModel(tipos);
        this.cmb_tipopax.setModel(tipo_paxs);
        this.cmb_posi.setModel(posiciones);

        this.setTitle("Oris-TKT");
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmb_tipo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txt_ticket = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_num_file = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_reemitido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_emd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_nombre_pax = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        txt_codigo_la = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_ruta = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        txt_fpago = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_segmentos = new javax.swing.JTable();
        btn_cancelar = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        date_fecha_emi = new com.toedter.calendar.JDateChooser();
        date_fecha_anu = new com.toedter.calendar.JDateChooser();
        date_fecha_ree = new com.toedter.calendar.JDateChooser();
        cmb_moneda = new javax.swing.JComboBox();
        cmb_estado = new javax.swing.JComboBox();
        cmb_tipopax = new javax.swing.JComboBox();
        txt_comision = new javax.swing.JFormattedTextField();
        txt_valor_neto = new javax.swing.JFormattedTextField();
        txt_valor_tax = new javax.swing.JFormattedTextField();
        txt_valor_final = new javax.swing.JFormattedTextField();
        txt_pnr = new javax.swing.JFormattedTextField();
        cmb_posi = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Tipo");

        cmb_tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tipoActionPerformed(evt);
            }
        });

        jLabel2.setText("Ticket");

        jLabel3.setText("PNR");

        txt_num_file.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_num_fileFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_num_fileFocusLost(evt);
            }
        });

        jLabel4.setText("N° File");

        jLabel5.setText("Ticket Reemitido");

        txt_reemitido.setText(" ");

        jLabel6.setText("Cod EMD");

        txt_emd.setText(" ");

        jLabel7.setText("Fecha Emision");

        jLabel8.setText("Fecha Anulacion");

        jLabel9.setText("Fecha Reemision");

        jLabel10.setText("Posicion");

        jLabel11.setText("Nombre Pasajero");

        txt_nombre_pax.setText(" ");

        jLabel12.setText("Tipo Pax");

        jLabel13.setText("Estado");

        jLabel15.setText("Codigo Linea");

        txt_codigo_la.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_codigo_laFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_codigo_laFocusLost(evt);
            }
        });

        jLabel16.setText("Ruta");

        jLabel17.setText("Moneda");

        jLabel18.setText("Comision");

        jLabel19.setText("Valor Neto");

        jLabel20.setText("Valor Tax");

        jLabel21.setText("Valor Final");

        jLabel22.setText("F Pago");

        table_segmentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(table_segmentos);

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        date_fecha_emi.setDateFormatString("dd/MM/yyyy");

        date_fecha_anu.setDateFormatString("dd/MM/yyyy");

        date_fecha_ree.setDateFormatString("dd/MM/yyyy");

        cmb_moneda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmb_estado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmb_tipopax.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txt_comision.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        txt_valor_neto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));

        txt_valor_tax.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));

        txt_valor_final.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        txt_valor_final.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_valor_finalFocusGained(evt);
            }
        });

        txt_pnr.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        cmb_posi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_posi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_posiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(22, 22, 22)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_valor_neto)
                            .addComponent(cmb_moneda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_comision)
                            .addComponent(txt_valor_tax))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_fpago)
                            .addComponent(txt_valor_final, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txt_num_file, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                                .addComponent(txt_pnr))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel6)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(cmb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel2)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_reemitido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                        .addComponent(txt_emd, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_ticket)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_nombre_pax))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(29, 29, 29))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel8))
                                            .addGap(16, 16, 16)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(date_fecha_emi, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                        .addComponent(date_fecha_anu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(date_fecha_ree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel13))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cmb_tipopax, 0, 72, Short.MAX_VALUE)
                                        .addComponent(cmb_estado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmb_posi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btn_guardar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_cancelar))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_codigo_la, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(date_fecha_anu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(date_fecha_ree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cmb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txt_ticket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_num_file, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(txt_reemitido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_emd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txt_pnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(date_fecha_emi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(cmb_posi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmb_tipopax)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(cmb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_nombre_pax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17)
                                .addComponent(cmb_moneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel19)
                                .addComponent(txt_valor_neto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(txt_comision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel20)
                                .addComponent(txt_valor_tax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txt_fpago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(txt_valor_final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_codigo_la, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txt_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar)
                    .addComponent(btn_guardar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        Ticket tic = new Ticket(this.txt_ticket.getText());
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
        if (txt_ticket.getText().trim().equals("")
                || date_fecha_emi.getDate() == null
                || this.txt_codigo_la.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "N° ticket, fecha emision y coódigo de linea aérea son obligatorios");
            return;
        }

        if (txt_comision.getText().equals("") || txt_comision.getText() == null) {
            txt_comision.setValue(new Double("0,00"));
        }
        if (txt_valor_neto.getText().equals("") || txt_valor_neto.getText() == null) {
            txt_valor_neto.setValue(new Double("0,00"));
        }
        if (txt_valor_tax.getText().equals("") || txt_valor_tax.getText() == null) {
            txt_valor_tax.setValue(new Double("0,00"));
        }
        if (txt_valor_final.getText().equals("") || txt_valor_final.getText() == null) {
            txt_valor_final.setValue(new Double("0,00"));
        }

        tic.setPnr(this.txt_pnr.getText());
        tic.setCodEmd(this.txt_emd.getText());
        tic.setNumFile(this.txt_num_file.getText());
        tic.setOldTicket(this.txt_reemitido.getText());
        tic.setTipo((String) this.cmb_tipo.getSelectedItem());
        tic.setFechaEmision(sdf.format(this.date_fecha_emi.getDate()));
        if (date_fecha_ree.getDate() != null) {
            tic.setFechaRemision(sdf.format(this.date_fecha_ree.getDate()));
        }
        if (date_fecha_anu.getDate() != null) {
            tic.setFechaAnulacion(sdf.format(this.date_fecha_anu.getDate()));
        }
        tic.setEstado((String) this.cmb_estado.getSelectedItem());
        tic.setPosicion((Integer) this.cmb_posi.getSelectedItem());
        tic.setTipoPasajero((String) this.cmb_tipopax.getSelectedItem());
        tic.setNombrePasajero(this.txt_nombre_pax.getText());
        tic.setMoneda((String) this.cmb_moneda.getSelectedItem());
        tic.setComision(((Number) this.txt_comision.getValue()).doubleValue());
        tic.setfPago(this.txt_fpago.getText());
        tic.setValorNeto(((Number) this.txt_valor_neto.getValue()).doubleValue());
        tic.setValorTasas(((Number) this.txt_valor_tax.getValue()).doubleValue());
        tic.setValorFinal(((Number) this.txt_valor_final.getValue()).doubleValue());
        tic.setRuta(this.txt_ruta.getText());
        tic.setcLineaAerea(this.txt_codigo_la.getText());

        System.out.println(tic);
        try {
            if (TicketDAO.getInstance().existeNumFile(tic)) {
                if (isNuevo) {
                    if (TicketDAO.getInstance().insertTicket(tic)) {

                    } else {
                        JOptionPane.showMessageDialog(this, "El N° Ticket ingresado ya existe!.");
                        return;
                    }
                } else {
                    TicketDAO.getInstance().updateTicket(tic);
                }
                this.isModificado = true;
                JOptionPane.showMessageDialog(this, "Los cambios se han guardado con exito.");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "El N°File ingresado no existe.");
            }
        } catch (SQLException e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error ,verifique los datos.");
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void cmb_posiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_posiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_posiActionPerformed

    private void cmb_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_tipoActionPerformed

    private void txt_num_fileFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_num_fileFocusGained
        
        System.out.println("focuseado\n");
        
        txt_num_file.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                System.out.println(txt_num_file.getText()+"\n");
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                System.out.println(txt_num_file.getText()+"\n");
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                System.out.println(txt_num_file.getText()+"\n");
            }
        }); 
    }//GEN-LAST:event_txt_num_fileFocusGained

    private void txt_num_fileFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_num_fileFocusLost
        
        System.out.println("a dejado de ser focuseado\n");
        
        if (txt_num_file.getText().length() > 0) {
            try {
                boolean existe;
                existe = TicketDAO.getInstance().existeNumFile(txt_num_file.getText());
                
                
                if (!existe) {
                    JOptionPane.showMessageDialog(null, "El num file no existe", "No encontrado", JOptionPane.WARNING_MESSAGE);
                    txt_num_file.setText("");
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(DetalleRegistro.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_txt_num_fileFocusLost

    private void txt_valor_finalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_valor_finalFocusGained
   
    }//GEN-LAST:event_txt_valor_finalFocusGained

    private void txt_codigo_laFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_codigo_laFocusGained
        
        System.out.println("focuseado");
        
        
        txt_codigo_la.getDocument().addDocumentListener(new DocumentListener() {

            
            @Override
            public void insertUpdate(DocumentEvent e) {
                System.out.println(txt_codigo_la.getText());

                
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                System.out.println(txt_codigo_la.getText());

            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                System.out.println(txt_codigo_la.getText());

            }


        
            
    });
        
        

    }//GEN-LAST:event_txt_codigo_laFocusGained

    private void txt_codigo_laFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_codigo_laFocusLost
        
        if (txt_codigo_la.getText().length() > 3) {
            JOptionPane.showMessageDialog(null, "El codigo de linea aerea no es válido", "Mensaje", JOptionPane.WARNING_MESSAGE);
            txt_codigo_la.setText("");
        }
    }//GEN-LAST:event_txt_codigo_laFocusLost

    public boolean isModificado() {
        return isModificado;
    }

    /**
     * @param args the command line arguments
     *
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JComboBox cmb_estado;
    private javax.swing.JComboBox cmb_moneda;
    private javax.swing.JComboBox cmb_posi;
    private javax.swing.JComboBox cmb_tipo;
    private javax.swing.JComboBox cmb_tipopax;
    private com.toedter.calendar.JDateChooser date_fecha_anu;
    private com.toedter.calendar.JDateChooser date_fecha_emi;
    private com.toedter.calendar.JDateChooser date_fecha_ree;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable table_segmentos;
    private javax.swing.JTextField txt_codigo_la;
    private javax.swing.JFormattedTextField txt_comision;
    private javax.swing.JTextField txt_emd;
    private javax.swing.JTextField txt_fpago;
    private javax.swing.JTextField txt_nombre_pax;
    private javax.swing.JTextField txt_num_file;
    private javax.swing.JFormattedTextField txt_pnr;
    private javax.swing.JTextField txt_reemitido;
    private javax.swing.JTextField txt_ruta;
    private javax.swing.JTextField txt_ticket;
    private javax.swing.JFormattedTextField txt_valor_final;
    private javax.swing.JFormattedTextField txt_valor_neto;
    private javax.swing.JFormattedTextField txt_valor_tax;
    // End of variables declaration//GEN-END:variables
}
